<!DOCTYPE html>
<!-- saved from url=(0043)http://ndesaintheme.com/edumix/version_1.2/ -->
<html class="" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>EDUMIX</title>
        <!-- <link rel="stylesheet" href="/css/foundation.css">
        <link rel="stylesheet" href="/css/dripicons.css">
        <link rel="stylesheet" href="/css/theme.css"> -->
        <link rel="stylesheet" href="/css/app.css">
    </head>
    <body>
        <div class="off-canvas-wrap" data-offcanvas="">
            <div class="inner-wrap">
                <div id="skin-select" style="width: 260px;">
                    <a id="toggle" class="">
                        <span class="fa icon-menu"></span>
                    </a>
                    <div class="skin-part" style="visibility: visible;">
                        <div id="tree-wrap">
                            <div class="profile" style="top: -13px;">
                                <img alt="" class="" src="/images/logo.png" style="width: 45px; height: 45px; top: 15px; left: 4px;">
                                <h3 style="display: block;">Budget <small>1.2</small></h3>
                            </div>
                            <div class="side-bar">
                                <ul id="menu-showhide" class="topnav slicknav" style="height: auto; margin: -13px 0px 0px;">
                                    <li style="text-align: left;">
                                        <a id="menu-select" class="tooltip-tip tooltipster-disable" href="http://ndesaintheme.com/edumix/version_1.2/index.html" title="Dashboard">
                                        <i class="icon-monitor" style="top: 0px; left: -15px; padding: 8px 0px;"></i>
                                        <span style="display: inline-block; float: none;">Dashboard</span>
                                        </a>
                                    </li>
                                    <li style="text-align: left;">
                                        <a class="tooltip-tip tooltipster-disable" href="http://ndesaintheme.com/edumix/version_1.2/#" title="Mail">
                                            <i class="icon-view-list" style="top: 0px; left: -15px; padding: 8px 0px;"></i>
                                            <span style="display: inline-block; float: none;">Transactions</span>
                                            <h4 style="display: inline-block; float: none;"><b class="fa fa-circle"></b></h4>
                                        </a>
                                    </li>
                                    <li style="text-align: left;">
                                        <a class="tooltip-tip tooltipster-disable" href="http://ndesaintheme.com/edumix/version_1.2/#" title="Mail">
                                            <i class="icon-export" style="top: 0px; left: -15px; padding: 8px 0px;"></i>
                                            <span style="display: inline-block; float: none;">Funds</span>
                                            <h4 style="display: inline-block; float: none;"><b class="fa fa-circle"></b></h4>
                                        </a>
                                    </li>
                                    <li style="text-align: left;">
                                        <a class="tooltip-tip tooltipster-disable" href="http://ndesaintheme.com/edumix/version_1.2/#" title="Mail">
                                            <i class="icon-graph-pie" style="top: 0px; left: -15px; padding: 8px 0px;"></i>
                                            <span style="display: inline-block; float: none;">Categories</span>
                                            <h4 style="display: inline-block; float: none;"><b class="fa fa-circle"></b></h4>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end of Rightsidemenu -->
                <div class="wrap-fluid" id="paper-bg" style="width: auto; margin-left: 260px;">
                    ...
                </div>
                <!-- End of Container Begin -->
            </div>
            <!-- end paper bg -->
        </div>
        <!-- end of off-canvas-wrap -->
        <!-- end of inner-wrap -->
        <!-- main javascript library -->
        <!-- <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/foundation.min.js"></script>
        <script type="text/javascript" src="/js/sliding-menu.js"></script> -->
        <script type="text/javascript" src="/js/app.js"></script>
        <script>
            $(document).foundation();
        </script>
    </body>
</html>
