<!doctype html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=11" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="google-site-verification" content="hIahgI8cltjkZ_8UcNp8vY5JO3ZKV3QxDcSzEy59HD0" />

        <title><?= $this->title ?></title>

        <?php $this->section('head') ?>
        <link rel="stylesheet" type="text/css" href="/css/app.css">
        <?php $this->stop() ?>
    </head>
    <body>
        <h1 class="show-for-sr">Budget</h1>
        <div class="top-bar">
            <div class="top-bar-left">
                <ul class="dropdown menu" data-dropdown-menu>
                    <li class="menu-text"><?= $this->translate('site_name') ?></li>
                    <li><a href="<?= $this->pathFor('transactions') ?>"><?= $this->translate('transactions_link') ?></a></li>
                    <li><a href="<?= $this->pathFor('funds') ?>"><?= $this->translate('funds_link') ?></a></li>
                    <li><a href="<?= $this->pathFor('categories') ?>"><?= $this->translate('categories_link') ?></a></li>
                </ul>
            </div>
            <div class="top-bar-right">
                <?php if ($this->currentUser): ?>
                    <form id="logout_form" method="post" action="<?= $this->pathFor('logout_post') ?>"><input type="hidden" name="_METHOD" value="DELETE"></form>

                    <ul class="dropdown menu" data-dropdown-menu>
                        <li>
                            <a href="#"><?= $this->currentUser->first_name ?></a>
                            <ul class="menu vertical">
                                <li><a href="<?= $this->pathFor('logout') ?>" onclick="$('form#logout_form').submit(); return false;"><?= $this->translate('logout_link') ?></a></li>
                            </ul>
                        </li>
                    </ul>
                <?php else: ?>
                    <ul class="menu">
                        <li><a href="<?= $this->pathFor('register') ?>"><?= $this->translate('register_link') ?></a></li>
                        <li><a href="<?= $this->pathFor('login') ?>"><?= $this->translate('login_link') ?></a></li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
        <div class="row">
            <div class="small-12 columns">

                <?php if (isset($this->messages['success'])): ?>
                <div class="success callout">
                    <?=$this->messages['success']; ?>
                </div>
                <?php endif; ?>

                <?php if (isset($this->messages['errors'])): ?>
                <div class="alert callout">
                    <ul>
                        <?php foreach ($this->messages['errors'] as $error): ?>
                        <li><?= $error ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <?php endif; ?>

                <?php $this->section('content') ?>
                <?php $this->stop() ?>
            </div>
        </div>

        <?php $this->section('scripts') ?>
        <script src="/js/app.js" type="text/javascript"></script>
        <?php $this->stop() ?>
    </body>
</html>
