<?php $this->layout('layouts/main', [
    'title' => 'Budget - Home',
    'selected_menu' => 'home',
]); ?>

<?php $this->section('content') ?>
    <ul>
        <li>Manage multiple funds of different curencies!</li>
        <li>Assign budgets to different categories</li>
        <li>Optimised for mobile devices too!</li>
    </ul>
<?php $this->replace() ?>

<?php $this->section('head') ?>
    <style>
    @media screen and (max-width: 40em) {
        .top-bar {
            display: none;
        }
    }
    </style>
<?php $this->append() ?>
