<?php $this->layout('layouts/main', [
    'title' => 'Budget',
    'selected_menu' => 'books',
]); ?>

<?php $this->section('breadcrumbs') ?>
    <li><a href="<?= $this->pathFor('books') ?>"><?= $this->translate('books_link') ?></a></li>
    <li><span class="show-for-sr">Current: </span> Create</li>
<?php $this->replace() ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="small-12 columns">
            <form id="book_form" method="post" action="<?= $this->pathFor('books_post') ?>">
                <?= $this->insert('books/partials/form') ?>

                <button class="button primary" type="submit">
                    <?= $this->translate('save_button') ?>
                </button>

                <a href="<?= $this->pathFor('books') ?>" class="button secondary"><?= $this->translate('cancel_button') ?></a>

                <?php if(isset($this->params['returnTo'])): ?>
                    <input type="hidden" name="returnTo" value="<?= $this->params['returnTo'] ?>">
                <?php endif ?>
            </form>
        </div>
    </div>
<?php $this->replace() ?>
