<?php $this->layout('layouts/main', [
    'title' => 'Budget',
    'selected_menu' => 'categories',
]); ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="small-12 columns">
            <form id="category_form" method="post" action="<?= $this->pathFor('categories_post') ?>">
                <?= $this->insert('categories/partials/form') ?>

                <button class="button primary" type="submit">
                    <?= $this->translate('save_button') ?>
                </button>

                <a href="<?= $this->pathFor('categories') ?>" class="button secondary"><?= $this->translate('cancel_button') ?></a>

                <?php if(isset($this->params['returnTo'])): ?>
                    <input type="hidden" name="returnTo" value="<?= $this->params['returnTo'] ?>">
                <?php endif ?>
            </form>
        </div>
    </div>
<?php $this->replace() ?>

<?php $this->section('scripts') ?>
    <script>
    $(function() {

        // init the autocomplete
        $.getJSON("/data/groups", function(data) {
            $("input[name='group']").autocomplete({
                source: data
            });
        });
    });
    </script>
<?php $this->append() ?>
