<?php $this->layout('layouts/main', [
    'title' => 'Budget',
]); ?>

<?php $this->section('content') ?>
    <div class="rows">
        <div class="small-12 medium-offset-10 medium-2 columns text-right">
            <a href="<?= $this->pathFor('categories_create') ?>" class="button expanded">New category</a>
        </div>
    </div>

    <div class="row">
        <div class="small-12 medium-12 columns">
            <table>
                <thead>
                    <tr>
                        <th><?= $this->translate('name') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->categories as $category): ?>
                        <tr>
                            <td><a href="<?= $this->pathFor('categories_edit', ['category_id' => $category->id]) ?>"><?= (($category->parent_id > 0) ? '- ' : '') . $category->name ?></a></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>

            <?= $this->insert('partials/pagination') ?>
        </div>
    </div>
<?php $this->replace() ?>
