<?php $this->layout('layouts/main', [
    'title' => 'Budget',
    'selected_menu' => 'transactions',
]); ?>

<?php $this->section('breadcrumbs') ?>
    <ul class="breadcrumbs">
        <li><i class="icon-home" style="color: #999;"></i></li>
        <li><a href="<?= $this->pathFor('transactions') ?>"><?= $this->translate('transactions_link') ?></a></li>
        <li><span class="show-for-sr">Current: </span> Create</li>
    </ul>
<?php $this->replace() ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="small-12 columns">
            <form id="transaction_form" method="post" action="<?= $this->pathFor('transactions_post') ?>">
                <?= $this->insert('transactions/partials/form') ?>

                <button class="button primary" type="submit">
                    <?= $this->translate('save_button') ?>
                </button>

                <a href="<?= $this->pathFor('transactions') ?>" class="button secondary"><?= $this->translate('cancel_button') ?></a>

                <?php if(isset($this->params['returnTo'])): ?>
                    <input type="hidden" name="returnTo" value="<?= $this->params['returnTo'] ?>">
                <?php endif ?>
            </form>
        </div>
    </div>
<?php $this->replace() ?>

<?php $this->section('scripts') ?>
    <script>
    $(function() {

        // init the datepicker
        $("input[name='purchased_at']").datepicker({
            dateFormat: "yy-mm-dd"
        });

        // init the autocomplete
        $.getJSON("/data/categories", function(data) {
            $("input[name='category']").autocomplete({
                source: data
            });
        });
    });
    </script>
<?php $this->append() ?>
