<?php $this->layout('layouts/main', [
    'title' => 'Budget',
    'selected_menu' => 'transactions',
]); ?>

<?php $this->section('breadcrumbs') ?>
    <li><a href="<?= $this->pathFor('transactions') ?>"><?= $this->translate('transactions_link') ?></a></li>
    <li><span class="show-for-sr">Current: </span> Create</li>
<?php $this->replace() ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="small-12 columns">
            <form id="transaction_form" method="post" action="<?= $this->pathFor('transactions_post') ?>">
                <?= $this->insert('transactions/partials/form') ?>

                <button class="button primary" type="submit">
                    <?= $this->translate('save_button') ?>
                </button>

                <a href="<?= $this->pathFor('transactions') ?>" class="button secondary"><?= $this->translate('cancel_button') ?></a>

                <?php if(isset($this->params['returnTo'])): ?>
                    <input type="hidden" name="returnTo" value="<?= $this->params['returnTo'] ?>">
                <?php endif ?>
            </form>
        </div>
    </div>
<?php $this->replace() ?>

<?php $this->section('scripts') ?>
    <script>
    $(function() {

        // init the datepicker
        $("input[name='purchased_at']").datepicker({
            dateFormat: "yy-mm-dd"
        });

        // // init the autocomplete
        // $.getJSON("/data/categories", function(data) {
        //     $("input[name='category']").autocomplete({
        //         source: data
        //     });
        // });

        // TODO move to app.js, remove from create/edit
        $("#new_tag_button").on("click", function(e) {
            var $newTag = $("input[name='new_tag']");
            var found = false;

            // if empty return
            if ($newTag.val() === "") {
                console.log("meow!");
                e.preventDefault();
                e.stopPropagation();
                return false;
            }

            // check if tag exists already. if so, check it.
            $("input[name='tags[]']").each(function(index, el) {
                if ($(el).val() === $newTag.val()) {
                    $(el).prop('checked', true);
                    found = true;
                    $newTag.val("");
                }
            });

            // create new tag and check it
            if (!found) {
                $("fieldset#tags").append('<input type="checkbox" name="tags[]" value="' + $newTag.val() + '" id="tag_' + (new Date()).getTime() + '" checked>' +
                '<label for="tag_' + (new Date()).getTime() + '">' + $newTag.val() + '</label>');
                $newTag.val("");
            }

            e.preventDefault();
            e.stopPropagation();
            return false;
        });

        // init tags
        $("input[name='tags']").tagsInput({
            width:'auto',
            height:'auto',
            autocomplete_url: '/data/tags',
            // defaultText: '',
        });
    });
    </script>
<?php $this->append() ?>

<?php $this->section('head') ?>
    <style>

    #tags input[type='checkbox'] {
        position: absolute;
        left: -9999px;
    }
    #tags label {
        display: inline-block;
        padding: 5px 10px;
        background: #767676;
        margin-bottom: 0.5rem;
        border-radius: 5px;
        color: #fff;
    }
    #tags label:hover {
        background: #5e5e5e;
    }
    #tags input[type='checkbox']:checked + label {
        background: #1779ba;
    }
    #tags input[type='checkbox']:checked + label:hover {
        background: #126195;
    }

    </style>
<?php $this->append() ?>
