<?php $this->layout('layouts/main', [
    'title' => 'Budget',
]); ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="small-12 columns">
            <form id="transaction_form" method="post" action="<?= $this->pathFor('transactions_update', ['transaction_id' => $this->transaction->id]) ?>">
                <?= $this->insert('transactions/partials/form') ?>

                <input type="hidden" name="_METHOD" value="PUT"/>

                <button class="button primary" type="submit">
                    <?= $this->translate('save_button') ?>
                </button>

                <a href="<?= $this->pathFor('transactions') ?>" class="button secondary"><?= $this->translate('cancel_button') ?></a>
            </form>
        </div>
    </div>
<?php $this->replace() ?>

<?php $this->section('scripts') ?>
    <script>

    // init the datepicker
    $(function() {
        $("input[name='purchased_at']").datepicker({
            dateFormat: "yyyy-mm-dd"
        });
    });

    // init the autocomplete
    $.getJSON("/data/categories", function(data) {
        $("input[name='category']").autocomplete({
            source: data
        });
    });
    </script>
<?php $this->append() ?>
