<?php $this->layout('layouts/main', [
    'title' => 'Budget',
    'selected_menu' => 'transactions',
]); ?>

<?php $this->section('breadcrumbs') ?>
    <li><a href="<?= $this->pathFor('transactions') ?>"><?= $this->translate('transactions_link') ?></a></li>
    <li><span class="show-for-sr">Current: </span> <?= $this->transaction->description ?></li>
<?php $this->replace() ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="small-12 columns">
            <form id="transaction_form" method="post" action="<?= $this->pathFor('transactions_update', ['transaction_id' => $this->transaction->id]) ?>">
                <?= $this->insert('transactions/partials/form') ?>

                <input type="hidden" name="_METHOD" value="PUT"/>

                <button class="button primary" type="submit">
                    <?= $this->translate('save_button') ?>
                </button>

                <a href="<?= $this->pathFor('transactions') ?>" class="button secondary"><?= $this->translate('cancel_button') ?></a>
            </form>

            <hr>

            <form method="POST" action="<?= $this->pathFor('transactions_delete', ['transaction_id' => $this->transaction->id]) ?>" onsubmit="return confirm('Are you sure you want to submit?');">
                <input type="hidden" name="_METHOD" value="DELETE"/>

                <input type="hidden" name="<?= $this->csrf_name ?>" value="<?= $this->csrf_value ?>">

                <button class="button alert" type="submit">
                    <?= $this->translate('delete_button') ?>
                </button>
            </form>
        </div>
    </div>
<?php $this->replace() ?>

<?php $this->section('scripts') ?>
    <script>

    // init the datepicker
    $(function() {
        $("input[name='purchased_at']").datepicker({
            dateFormat: "yyyy-mm-dd"
        });

        // init tags
        $("input[name='tags']").tagsInput({
            width:'auto',
            height:'auto',
            autocomplete_url: '/data/tags'
        });

        // init the autocomplete
        $.getJSON("/data/categories", function(data) {
            $("input[name='category']").autocomplete({
                source: data
            });
        });
    });
    </script>
<?php $this->append() ?>
