<?php $this->layout('layouts/main', [
    'title' => 'Budget',
]); ?>

<?php $this->section('content') ?>
    <div class="rows">
        <div class="small-12 medium-2 columns">
            <form id="switch_fund_form" method="post" action="<?= $this->pathFor('funds_switch') ?>">
                <label class="show-for-sr"><?= $this->translate('fund_label') ?></label>
                <select name="fund_id">
                    <?php foreach($this->funds as $fund): ?>
                        <option value="<?= $fund->id ?>" <?= ($this->current_fund->id == $fund->id) ? 'selected' : '' ?>><?= $fund->name ?></option>
                    <?php endforeach ?>
                </select>
                <submit type="submit" class="button show-for-sr"><?= $this->translate('switch_fund_button') ?></submit>
            </form>
        </div>
        <div class="small-12 medium-offset-8 medium-2 columns text-right">
            <a href="<?= $this->pathFor('transactions_create') ?>" class="button expanded"><?= $this->translate('new_translation_button') ?></a>
        </div>
    </div>

    <div class="row">
        <div class="small-12 medium-8 columns">
            <form class="callout secondary" method="get" action="<?= $this->pathFor('transactions') ?>">
                <div class="row">
                    <div class="small-12 medium-3 columns">
                        <label class="show-for-sr"><?= $this->translate('start_date_label') ?></label>
                        <input type="text" name="start_date" value="<?= $this->start_date ?>" placeholder="YYYY-MM-DD">
                    </div>
                    <div class="small-12 medium-3 columns">
                        <label class="show-for-sr"><?= $this->translate('end_date_label') ?></label>
                        <input type="text" name="end_date" value="<?= $this->end_date ?>" placeholder="YYYY-MM-DD">
                    </div>
                    <div class="small-12 medium-6 columns">
                        <button type="submit" class="button"><?= $this->translate('set_filter_button') ?></button>
                    </div>
                </div>
                <input type="hidden" name="page" value="<?= $this->page ?>">
            </form>

            <table>
                <thead>
                    <tr>
                        <th><?= $this->translate('description_header') ?></th>
                        <th width="15%"><?= $this->translate('date_header') ?></th>
                        <th width="15%"><?= $this->translate('amount_header') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->transactions as $transaction): ?>
                        <tr>
                            <td><a href="<?= $this->pathFor('transactions_edit', ['transaction_id' => $transaction->id]) ?>"><?= $transaction->description ?></a></td>
                            <td><?= $transaction->purchased_at ?></td>
                            <td><?= sprintf($this->current_fund->currency->format, $transaction->amount) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="2"><?= $this->translate('total_header') ?></th>
                        <td><?= sprintf($this->current_fund->currency->format, $this->total_amount) ?></td>
                    </tr>
                </tfoot>
            </table>

            <?= $this->insert('partials/pagination') ?>
        </div>
        <div class="small-12 medium-4 columns">
            <div id="container" style="min-width: 310px; max-width: 600px; height: 400px; margin: 0 auto"></div>
        </div>
    </div>
<?php $this->replace() ?>

<?php $this->section('scripts') ?>
    <script>

    // init the fund switcher
    $("select[name='fund_id']").on("change", function() {
        $('form#switch_fund_form').submit();
    });

    // init the datepicker
    $(function() {
        $("input[name='start_date'],input[name='end_date']").datepicker({
            dateFormat: "yyyy-mm-dd"
        });
    });

    // init the chart
    $.getJSON("/data/expenses", function(data) {

        console.log(data);

        Highcharts.chart('container', {
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Expenses'
            },
            plotOptions: data['plotOptions'],
            tooltip: data["tooltip"],
            series: data["series"],
            drilldown: data["drilldown"]
        });
    });

    // Highcharts.chart('container', {
    //     chart: {
    //         type: 'pie'
    //     },
    //     title: {
    //         text: 'Expenses'
    //     },
    //     plotOptions: {
    //         series: {
    //             dataLabels: {
    //                 enabled: true,
    //                 format: '{point.name}: {point.y:.1f}%'
    //             }
    //         }
    //     },
    //     tooltip: {
    //         headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
    //         pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
    //     },
    //     series: [{
    //         name: 'Groups',
    //         colorByPoint: true,
    //         data: [{
    //             name: 'Food',
    //             y: 30,
    //             drilldown: '1'
    //         }, {
    //             name: 'Chrome',
    //             y: 24.03,
    //             drilldown: 'Chrome'
    //         }, {
    //             name: 'Firefox',
    //             y: 10.38,
    //             drilldown: 'Firefox'
    //         }, {
    //             name: 'Safari',
    //             y: 4.77,
    //             drilldown: 'Safari'
    //         }, {
    //             name: 'Opera',
    //             y: 0.91,
    //             drilldown: 'Opera'
    //         }, {
    //             name: 'Other',
    //             y: 0.2,
    //             drilldown: null
    //         }]
    //     }],
    //     drilldown: {
    //         series: [{
    //             name: 'Food',
    //             id: '1',
    //             data: [
    //                 ['Groceries', 15],
    //                 ['Bento', 10],
    //                 ['Resturant', 5],
    //             ]
    //         }, {
    //             name: 'Chrome',
    //             id: 'Chrome',
    //             data: [
    //                 ['v40.0', 5],
    //                 ['v41.0', 4.32],
    //                 ['v42.0', 3.68],
    //                 ['v39.0', 2.96],
    //                 ['v36.0', 2.53],
    //                 ['v43.0', 1.45],
    //                 ['v31.0', 1.24],
    //                 ['v35.0', 0.85],
    //                 ['v38.0', 0.6],
    //                 ['v32.0', 0.55],
    //                 ['v37.0', 0.38],
    //                 ['v33.0', 0.19],
    //                 ['v34.0', 0.14],
    //                 ['v30.0', 0.14]
    //             ]
    //         }, {
    //             name: 'Firefox',
    //             id: 'Firefox',
    //             data: [
    //                 ['v35', 2.76],
    //                 ['v36', 2.32],
    //                 ['v37', 2.31],
    //                 ['v34', 1.27],
    //                 ['v38', 1.02],
    //                 ['v31', 0.33],
    //                 ['v33', 0.22],
    //                 ['v32', 0.15]
    //             ]
    //         }, {
    //             name: 'Safari',
    //             id: 'Safari',
    //             data: [
    //                 ['v8.0', 2.56],
    //                 ['v7.1', 0.77],
    //                 ['v5.1', 0.42],
    //                 ['v5.0', 0.3],
    //                 ['v6.1', 0.29],
    //                 ['v7.0', 0.26],
    //                 ['v6.2', 0.17]
    //             ]
    //         }, {
    //             name: 'Opera',
    //             id: 'Opera',
    //             data: [
    //                 ['v12.x', 0.34],
    //                 ['v28', 0.24],
    //                 ['v27', 0.17],
    //                 ['v29', 0.16]
    //             ]
    //         }]
    //     }
    // });

    </script>
<?php $this->append() ?>
