<?php

$currencyFormat = $this->current_fund->currency->format;

$this->layout('layouts/main', [
    'title' => 'Budget',
    'selected_menu' => 'transactions',
]); ?>

<?php $this->section('breadcrumbs') ?>
    <li>
        <span class="show-for-sr">Current: </span> Transactions
    </li>
<?php $this->replace() ?>

<?php $this->section('content') ?>
    <div class="rows">
        <?= $this->insert('partials/filters') ?>

        <div class="small-12 medium-3 columns">
            <a href="<?= $this->pathFor('transactions_create') ?>" class="button expanded">
                <i class="fa fa-plus" aria-hidden="true"></i>
                <?= $this->translate('new_transaction_button') ?>
            </a>
        </div>
    </div>

    <div class="row">
        <div class="small-12 medium-12 columns">
            <table>
                <thead>
                    <tr>
                        <th>
                            <?= $this->generateSortLink($this->translate('description_header'), 'description', $this->selected_column) ?>
                        </th>
                        <th width="15%">
                            <?= $this->generateSortLink($this->translate('amount_header'), 'amount', $this->selected_column) ?>
                        </th>
                        <th width="15%" class="hide-for-small-only">
                            <?= $this->generateSortLink($this->translate('category_header'), 'category', $this->selected_column) ?>
                        </th>
                        <th width="15%">
                            <?= $this->generateSortLink($this->translate('date_header'), 'purchased_at', $this->selected_column) ?>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->transactions as $transaction): ?>
                        <tr>
                            <td>
                                <a href="<?= $this->pathFor('transactions_edit', ['transaction_id' => $transaction->id]) ?>"><?= $transaction->description ?></a>
                                <?php foreach ($transaction->tags as $tag): ?>
                                    <span class="tag">#<?= $tag->name ?></span>
                                <?php endforeach ?>
                            </td>
                            <td><?= sprintf($currencyFormat, $transaction->amount) ?></td>
                            <td class="hide-for-small-only"><?= $transaction->category->name ?></td>
                            <td><?= $transaction->purchased_string ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th><?= $this->translate('total_header') ?></th>
                        <td><?= sprintf($currencyFormat, $this->total_amount) ?></td>
                    </tr>
                </tfoot>
            </table>

            <?= $this->insert('partials/pagination') ?>
        </div>
    </div>
<?php $this->replace() ?>
