<?php $this->layout('layouts/main', [
    'title' => 'Budget',
]); ?>

<?php $this->section('content') ?>
    <div class="rows">
        <div class="small-12 medium-2 columns">
            <form id="switch_fund_form" method="post" action="<?= $this->pathFor('funds_switch') ?>">
                <label class="show-for-sr"><?= $this->translate('fund_label') ?></label>
                <select name="fund_id">
                    <?php foreach($this->funds as $fund): ?>
                        <option value="<?= $fund->id ?>" <?= ($this->current_fund->id == $fund->id) ? 'selected' : '' ?>><?= $fund->name ?></option>
                    <?php endforeach ?>
                </select>
                <submit type="submit" class="button show-for-sr"><?= $this->translate('switch_fund_button') ?></submit>
            </form>
        </div>
        <div class="small-12 medium-offset-8 medium-2 columns text-right">
            <a href="<?= $this->pathFor('transactions_create') ?>" class="button expanded"><?= $this->translate('new_translation_button') ?></a>
        </div>
    </div>

    <div class="row">
        <div class="small-12 medium-8 columns">
            <form class="callout secondary" method="get" action="<?= $this->pathFor('transactions') ?>">
                <div class="row">
                    <div class="small-12 medium-3 columns">
                        <label class="show-for-sr"><?= $this->translate('start_date_label') ?></label>
                        <input type="text" name="start_date" value="<?= $this->start_date ?>" placeholder="YYYY-MM-DD">
                    </div>
                    <div class="small-12 medium-3 columns">
                        <label class="show-for-sr"><?= $this->translate('end_date_label') ?></label>
                        <input type="text" name="end_date" value="<?= $this->end_date ?>" placeholder="YYYY-MM-DD">
                    </div>
                    <div class="small-12 medium-6 columns">
                        <button type="submit" class="button"><?= $this->translate('set_filter_button') ?></button>
                    </div>
                </div>
                <input type="hidden" name="page" value="<?= $this->page ?>">
            </form>

            <table>
                <thead>
                    <tr>
                        <th><?= $this->translate('description_header') ?></th>
                        <th width="15%"><?= $this->translate('date_header') ?></th>
                        <th width="15%"><?= $this->translate('amount_header') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->transactions as $transaction): ?>
                        <tr>
                            <td><a href="<?= $this->pathFor('transactions_edit', ['transaction_id' => 1]) ?>"><?= $transaction->description ?></a></td>
                            <td><?= $transaction->purchased_at ?></td>
                            <td><?= sprintf($this->current_fund->currency->format, $transaction->amount) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="2"><?= $this->translate('total_header') ?></th>
                        <td><?= sprintf($this->current_fund->currency->format, $this->total_amount) ?></td>
                    </tr>
                </tfoot>
            </table>

            <?= $this->insert('partials/pagination') ?>
        </div>
        <div class="small-12 medium-4 columns">
            <div id="container" style="min-width: 310px; max-width: 600px; height: 400px; margin: 0 auto"></div>
        </div>
    </div>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/drilldown.js"></script>
<?php $this->replace() ?>

<?php $this->section('scripts') ?>
    <script>
    $("select[name='fund_id']").on("change", function() {
        $('form#switch_fund_form').submit();
    });
    $(function() {
        $("input[name='start_date'],input[name='end_date']").datepicker();
    });
    </script>
<?php $this->append() ?>
