<?php $this->layout('layouts/main', [
    'title' => 'Budget',
]); ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="small-12 columns">
            <form id="fund_form" method="post" action="<?= $this->pathFor('funds_post') ?>">
                <?= $this->insert('funds/partials/form') ?>

                <button class="button primary" type="submit">
                    <?= $this->translate('save_button') ?>
                </button>

                <a href="<?= $this->pathFor('funds') ?>" class="button secondary"><?= $this->translate('cancel_button') ?></a>
            </form>

            <hr>

            <form method="POST" action="<?= $this->pathFor('funds_delete', ['fund_id' => $this->fund->id]) ?>" onsubmit="return confirm('Are you sure you want to submit?');">
                <input type="hidden" name="_METHOD" value="DELETE"/>

                <button class="button alert" type="submit">
                    <?= $this->translate('delete_button') ?>
                </button>
            </form>
        </div>
    </div>
<?php $this->replace() ?>
