<?php $this->layout('layouts/main', [
    'title' => 'Budget',
    'selected_menu' => 'funds',
]); ?>

<?php $this->section('breadcrumbs') ?>
    <li><a href="<?= $this->pathFor('funds') ?>"><?= $this->translate('funds_link') ?></a></li>
    <li><span class="show-for-sr">Current: </span> <?= $this->fund->name ?></li>
<?php $this->replace() ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="small-12 columns">
            <form id="fund_form" method="post" action="<?= $this->pathFor('funds_update', ['fund_id' => $this->fund->id]) ?>">
                <?= $this->insert('funds/partials/form') ?>

                <input type="hidden" name="_METHOD" value="PUT"/>

                <button class="button primary" type="submit">
                    <?= $this->translate('save_button') ?>
                </button>

                <a href="<?= $this->pathFor('funds') ?>" class="button secondary"><?= $this->translate('cancel_button') ?></a>
            </form>

            <hr>

            <form method="POST" action="<?= $this->pathFor('funds_delete', ['fund_id' => $this->fund->id]) ?>" onsubmit="return confirm('Are you sure you want to submit?');">
                <input type="hidden" name="_METHOD" value="DELETE"/>

                <input type="hidden" name="<?= $this->csrf_name ?>" value="<?= $this->csrf_value ?>">

                <button class="button alert" type="submit">
                    <?= $this->translate('delete_button') ?>
                </button>
            </form>
        </div>
    </div>
<?php $this->replace() ?>
