<?php $this->layout('layouts/main', [
    'title' => 'Budget',
]); ?>

<?php $this->section('content') ?>
    <div class="rows">
        <div class="small-12 medium-offset-10 medium-2 columns text-right">
            <a href="<?= $this->pathFor('funds_create') ?>" class="button expanded">New fund</a>
        </div>
    </div>

    <div class="row">
        <div class="small-12 medium-12 columns">
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th width="15%">Currency</th>
                        <th width="15%">Balance</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->funds as $fund): ?>
                        <tr>
                            <td><a href="<?= $this->pathFor('funds_edit', ['fund_id' => 1]) ?>"><?= $fund->description ?></a></td>
                            <td><?= $fund->purchased_at ?></td>
                            <td><?= sprintf('&pound;%01.2f', $fund->balance) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>

            <?= $this->insert('partials/pagination') ?>
        </div>
    </div>
<?php $this->replace() ?>
