<?php $this->layout('layouts/main', [
    'title' => 'Budget',
    'selected_menu' => 'funds',
]); ?>

<?php $this->section('breadcrumbs') ?>
    <ul class="breadcrumbs">
        <li><i class="icon-home" style="color: #999;"></i></li>
        <li>
            <span class="show-for-sr">Current: </span> Funds
        </li>
    </ul>
<?php $this->replace() ?>

<?php $this->section('content') ?>
    <div class="rows">
        <div class="small-12 medium-offset-10 medium-2 columns text-right">
            <a href="<?= $this->pathFor('funds_create') ?>" class="button expanded">
                <i class="fa fa-plus" aria-hidden="true"></i>
                <?= $this->translate('new_fund_button') ?>
            </a>
        </div>
    </div>

    <div class="row">
        <div class="small-12 medium-12 columns">
            <table>
                <thead>
                    <tr>
                        <th><?= $this->translate('name_header') ?></th>
                        <th width="15%"><?= $this->translate('currency_header') ?></th>
                        <th width="15%"><?= $this->translate('balance_header') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->funds as $fund): ?>
                        <tr>
                            <td><a href="<?= $this->pathFor('funds_edit', ['fund_id' => $fund->id]) ?>"><?= $fund->name ?></a></td>
                            <td><?= $fund->purchased_at ?></td>
                            <td class="<?= (($fund->getAmount() > 0) ? 'balance-in' : (($fund->getAmount() < 0) ? 'balance-out' : 'balance-even')) ?>"><?= sprintf($fund->currency->format, $fund->getAmount()) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>

            <?= $this->insert('partials/pagination') ?>
        </div>
    </div>
<?php $this->replace() ?>
