<?php $this->layout('layouts/main', [
    'title' => 'Budget',
]); ?>

<?php $this->section('content') ?>
    <div class="rows">
        <div class="small-12 medium-12 columns text-right">
            <a href="<?= $this->pathFor('funds_create') ?>" class="button">New fund</a>
        </div>
    </div>

    <div class="row">
        <div class="small-12 medium-12 columns">
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th width="15%">Balance</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><a href="<?= $this->pathFor('funds_edit', ['fund_id' => 1]) ?>">Nationwide</a></td>
                        <td>&pound;12.50</td>
                    </tr>
                </tbody>
            </table>

            <ul class="pagination" role="navigation" aria-label="Pagination">
                <li class="pagination-previous disabled">Previous <span class="show-for-sr">page</span></li>
                <li class="current"><span class="show-for-sr">You're on page</span> 1</li>
                <li><a href="#" aria-label="Page 2">2</a></li>
                <li><a href="#" aria-label="Page 3">3</a></li>
                <li><a href="#" aria-label="Page 4">4</a></li>
                <li class="ellipsis" aria-hidden="true"></li>
                <li><a href="#" aria-label="Page 12">12</a></li>
                <li><a href="#" aria-label="Page 13">13</a></li>
                <li class="pagination-next"><a href="#" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
            </ul>
        </div>
    </div>
<?php $this->replace() ?>
