<?php

$currencyFormat = $this->current_fund->currency->format;

$this->layout('layouts/main', [
    'title' => 'Budget',
    'selected_menu' => 'tags',
]); ?>

<?php $this->section('breadcrumbs') ?>
    <li>
        <span class="show-for-sr">Current: </span> Tags
    </li>
<?php $this->replace() ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="small-12 medium-12 columns">
            <table>
                <thead>
                    <tr>
                        <th><?= $this->translate('name_header') ?></th>
                        <th width="15%"><?= $this->translate('amount_header') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->tags as $tag):
                        $transactionsAmount = $tag->transactions()->pluck('amount')->sum() ?>
                        <tr>
                            <td><?= $tag->name ?></td>
                            <td><?= sprintf($currencyFormat, $transactionsAmount) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>

            <?= $this->insert('partials/pagination') ?>
        </div>
    </div>
<?php $this->replace() ?>
