<form id="filters_form" method="get" action="" style="display: inline;">
    <?php if ($this->select_month_options): ?>
        <div class="small-12 medium-3 columns">
            <label class="show-for-sr"><?= $this->translate('month_label') ?></label>
            <select name="month">
                <option value=""><?= $this->translate('all_months') ?></option>
                <?php foreach ($this->select_month_options as $ym => $month): ?>
                    <option value="<?= $ym ?>" <?= ($ym == @$this->query['month']) ? 'selected="selected"' : '' ?>> <?= $month ?></option>
                <?php endforeach ?>
            </select>
        </div>
    <?php endif ?>

    <?php if ($this->select_category_options): ?>
        <div class="small-12 medium-3 columns">
            <label class="show-for-sr"><?= $this->translate('categories_label') ?></label>
            <select name="category">
                <option value=""><?= $this->translate('all_categories') ?></option>
                <?php foreach ($this->select_category_options as $category): ?>
                    <option value="<?= $category->id ?>" <?= ($category->id == @$this->query['category']) ? 'selected="selected"' : '' ?>><?= $category->name ?></option>
                <?php endforeach ?>
            </select>
        </div>
    <?php endif ?>

    <?php if ($this->select_tag_options): ?>
        <div class="small-12 medium-3 columns">
            <label class="show-for-sr"><?= $this->translate('tag_label') ?></label>
            <select name="tag">
                <option value=""><?= $this->translate('all_tags') ?></option>
                <?php foreach($this->select_tag_options as $tag): ?>
                    <option value="<?= $tag->id ?>" <?= (@$this->query['tag'] == $tag->id) ? 'selected' : '' ?>><?= $tag->name ?></option>
                <?php endforeach ?>
            </select>
        </div>
    <?php endif ?>

    <submit type="submit" class="show-for-sr"><?= $this->translate('filter_button') ?></submit>
</form>
