<?php if ($this->total_pages > 1): ?>
    <ul class="pagination" role="navigation" aria-label="Pagination">
        <?php if ($this->page > 1): ?>
            <li class="pagination-previous"><a href="?<?= $this->generateQueryString(['page'=>($this->page-1)]) ?>" aria-label="Next page"><?= $this->translate('pagination_previous') ?></a></li>
        <?php else: ?>
            <li class="pagination-previous disabled"><?= $this->translate('pagination_previous') ?></li>
        <?php endif; ?>

        <?php for($p=1; $p <= $this->total_pages; $p++): ?>
            <?php if ($this->page == $p): ?>
                <li class="current"><?= sprintf($this->translate('pagination_youre_on_page'), $this->page) ?></li>
            <?php else: ?>
                <li><a href="?<?= $this->generateQueryString(['page'=>$p]) ?>" aria-label="Page <?= $p ?>"><?= $p ?></a></li>
            <?php endif ?>
        <?php endfor ?>

        <?php if ($this->page < $this->total_pages): ?>
            <li class="pagination-next"><a href="?<?= $this->generateQueryString(['page'=>(++$this->page)]) ?>" aria-label="Next page"><?= $this->translate('pagination_next') ?></a></li>
        <?php else: ?>
            <li class="pagination-next disabled"><?= $this->translate('pagination_next') ?></li>
        <?php endif; ?>
    </ul>
<?php endif ?>
