<?php
$currencyFormat = $this->current_fund->currency->format;
?>
<div class="small-12 medium-12 columns widget widget__current-month-stats responsive-overflow">
    <h3><?= $this->translate('current_month_stats_header') ?></h3>
    <table class="unstriped">
        <thead>
            <tr>
                <th><span class="show-for-sr"><?= $this->translate('month_header') ?></span></th>
                <th width="20%"><?= $this->translate('earnings_header') ?></th>
                <th width="20%"><?= $this->translate('expenses_header') ?></th>
                <th width="20%"><?= $this->translate('balance_header') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->widget_data as $month => $data):
                $earningsAmount = $data['earnings']['amount'];
                $expensesAmount = $data['expenses']['amount'];
                $balance = $data['balance']['amount']; ?>
            <tr>
                <td><a href="<?= $this->pathFor('transactions') ?>?month=<?= $month ?>"><?= date('M', strtotime($month . '-01')) ?> <span class="hide-for-small-only"><?= date('Y', strtotime($month . '-01')) ?></span></a></td>
                <td><?= sprintf($currencyFormat, $earningsAmount) ?></td>
                <td><?= sprintf($currencyFormat, $expensesAmount) ?></td>
                <td class="<?= $this->balanceClass($balance) ?>"><?= sprintf($currencyFormat, $balance) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
