<?php
$currencyFormat = $this->current_fund->currency->format;

// calculate the average
$averageEarningsMonths = 0;
$averageEarningsTotal = 0;
$averageExpensesMonths = 0;
$averageExpensesTotal = 0;
$averageBalanceMonths = 0;
$averageBalanceTotal = 0;
foreach ($this->widget_data as $month => $data) {

    // we won't bother with the current month
    if ($month !== date('Y-m')) {
        $averageEarningsMonths++;
        $averageEarningsTotal+= $data['earnings']['amount'];
        $averageExpensesMonths++;
        $averageExpensesTotal+= $data['expenses']['amount'];
        $averageBalanceMonths++;
        $averageBalanceTotal+= $data['balance']['amount'];
    }
}

?>
<div class="small-12 medium-12 columns widget widget__previous-month-stats responsive-overflow">
    <h3><?= $this->translate('previous_month_stats_header') ?></h3>

    <?php if (count($this->widget_data) > 0): ?>
        <table class="unstriped">
            <thead>
                <tr>
                    <th><span class="show-for-sr"><?= $this->translate('month_header') ?></span></th>
                    <th><?= $this->translate('earnings_header') ?></th>
                    <th><?= $this->translate('expenses_header') ?></th>
                    <th><?= $this->translate('balance_header') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->widget_data as $month => $data):
                    $earningsAmount = $data['earnings']['amount'];
                    $expensesAmount = $data['expenses']['amount'];
                    $balance = $data['balance']['amount']; ?>
                <tr>
                    <?php if ($earningsAmount || $expensesAmount): ?>
                        <td><a href="<?= $this->pathFor('transactions') ?>?filter__month=<?= $month ?>"><?= date('M', strtotime($month . '-01')) ?> <span class="hide-for-small-only"><?= date('Y', strtotime($month . '-01')) ?></span></a></td>
                    <?php endif; ?>
                    <td><?= sprintf($currencyFormat, $earningsAmount) ?></td>
                    <td><?= sprintf($currencyFormat, $expensesAmount) ?></td>
                    <td class="<?= $this->balanceClass($balance) ?>"><?= sprintf($currencyFormat, $balance) ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
            <?php if ($averageBalanceMonths > 0): ?>
                <tfoot>
                    <tr>
                        <th><?= $this->translate('average_header') ?></th>
                        <td><?= sprintf($currencyFormat, ($averageEarningsTotal/$averageEarningsMonths)) ?></td>
                        <td><?= sprintf($currencyFormat, ($averageExpensesTotal/$averageExpensesMonths)) ?></td>
                        <td><?= sprintf($currencyFormat, ($averageBalanceTotal/$averageBalanceMonths)) ?></td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('year_projection_header') ?></th>
                        <td><?= sprintf($currencyFormat, ($averageEarningsTotal/$averageEarningsMonths) * 12) ?>*</td>
                        <td><?= sprintf($currencyFormat, ($averageExpensesTotal/$averageExpensesMonths) * 12) ?>*</td>
                        <td><?= sprintf($currencyFormat, ($averageBalanceTotal/$averageBalanceMonths) * 12) ?>*</td>
                    </tr>
                    <tr>
                        <th><?= $this->translate('3_year_projection_header') ?></th>
                        <td><?= sprintf($currencyFormat, ($averageEarningsTotal/$averageEarningsMonths) * 36) ?>*</td>
                        <td><?= sprintf($currencyFormat, ($averageExpensesTotal/$averageExpensesMonths) * 36) ?>*</td>
                        <td><?= sprintf($currencyFormat, ($averageBalanceTotal/$averageBalanceMonths) * 36) ?>*</td>
                    </tr>
                </tfoot>
            <?php endif ?>
        </table>
    <?php else: ?>
            <p><?= $this->translate('previous_months_not_found') ?></p>
    <?php endif ?>
</div>
