<?php
$currencyFormat = $this->current_fund->currency->format;
?>
<div class="small-12 medium-12 columns widget widget__recent-transactions">
    <h3><?= $this->translate('recent_transactions') ?></h3>
    <table class="unstriped">
        <thead>
            <tr>
                <th><span class="show-for-sr"><?= $this->translate('month_header') ?></span></th>
                <th><?= $this->translate('amount_header') ?></th>
                <th><?= $this->translate('date_header') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->widget_data as $transaction): ?>
                <tr>
                    <td>
                        <a href="<?= $this->pathFor('transactions_edit', ['transaction_id' => $transaction->id]) ?>"><?= $transaction->description ?></a>
                    </td>
                    <td><?= sprintf($currencyFormat, $transaction->amount) ?></td>
                    <td><?= $transaction->purchased_string ?></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
