<?php
$currencyFormat = $this->current_fund->currency->format;
?>
<div class="small-12 medium-12 columns widget widget__yearly-stats">
    <h3><?= $this->translate('yearly_stats_header') ?></h3>
    <table class="unstriped">
        <thead>
            <tr>
                <th><span class="show-for-sr"><?= $this->translate('year_header') ?></span></th>
                <th><?= $this->translate('earnings_header') ?></th>
                <th><?= $this->translate('expenses_header') ?></th>
                <th><?= $this->translate('balance_header') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->widget_data as $year => $data):
                $earningsAmount = $data['earnings']['amount'];
                $expensesAmount = $data['expenses']['amount'];
                $balance = $data['balance']['amount']; ?>
            <tr>
                <?php if ($earningsAmount || $expensesAmount): ?>
                    <td><a href="<?= $this->pathFor('transactions') ?>?filter__month=<?= $year ?>"><?= $year ?></a></td>
                <?php endif; ?>
                <td><?= sprintf($currencyFormat, $earningsAmount) ?></td>
                <td><?= sprintf($currencyFormat, $expensesAmount) ?></td>
                <td class="<?= $this->balanceClass($balance) ?>"><?= sprintf($currencyFormat, $balance) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
