<label><?= $this->translate('description_label') ?>
    <input type="text" name="description" placeholder="<?= $this->translate('description_label') ?>" value="<?= @$this->params['description'] ?>">
</label>

<label><?= $this->translate('amount_label') ?>
    <input type="text" name="amount" placeholder="<?= $this->translate('amount_label') ?>" value="<?= @$this->params['amount'] ?>">
</label>

<label><?= $this->translate('category_label') ?>
    <input type="text" name="category" placeholder="<?= $this->translate('category_label') ?>" value="<?= @$this->params['category'] ?>">
</label>

<label><?= $this->translate('purchased_at_label') ?>
    <input type="text" name="purchased_at" placeholder="<?= $this->translate('purchased_at_label') ?>" value="<?= @$this->params['purchased_at'] ?>">
</label>

<fieldset id="tags">
    <legend><?= $this->translate('tags_label') ?></legend>
    <?php foreach ($this->tags as $tagName): ?>
        <input type="checkbox" name="tags[]" value="<?= $tagName ?>" id="tag__<?= md5($tagName) ?>" <?php if (is_array(@$this->params['tags']) && in_array($tagName, $this->params['tags'])): ?> checked<?php endif ?>>
        <label for="tag__<?= md5($tagName) ?>"><?= $tagName ?></label>
    <?php endforeach ?>
</fieldset>

<div class="row collapse">
    <div class="small-10 columns">
        <input type="text" name="new_tag">
    </div>
    <div class="small-2 columns">
        <button class="button postfix" id="new_tag_button"><?= $this->translate('create_new_tag') ?></button>
    </div>
</div>

<input type="hidden" name="<?= $this->csrf_name ?>" value="<?= $this->csrf_value ?>">
