<label><?= $this->translate('description_label') ?>
    <input type="text" name="description" placeholder="<?= $this->translate('description_label') ?>" value="<?= @$this->params['description'] ?>">
</label>

<label><?= $this->translate('amount_label') ?>
    <input type="text" name="amount" placeholder="<?= $this->translate('amount_label') ?>" value="<?= @$this->params['amount'] ?>">
</label>

<label><?= $this->translate('category_label') ?>
    <input type="text" name="category" placeholder="<?= $this->translate('category_label') ?>" value="<?= @$this->params['category'] ?>">
</label>

<label><?= $this->translate('purchased_at_label') ?>
    <input type="text" name="purchased_at" placeholder="<?= $this->translate('purchased_at_label') ?>" value="<?= @$this->params['purchased_at'] ?>">
</label>

<label style="margin-bottom: 1rem;"><?= $this->translate('tags_label') ?>
    <input type="text" name="tags" placeholder="<?= $this->translate('tags_label') ?>" value="<?= @$this->params['tags'] ?>">
</label>

<input type="hidden" name="<?= $this->csrf_name ?>" value="<?= $this->csrf_value ?>">
